exclude: "docs/.*"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
        exclude: "^.vscode/settings.json$"
      - id: fix-byte-order-marker
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-added-large-files # check for file bigger than 500kb
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.16"
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/trim21/dprint-pre-commit
    rev: "v0.51.1.0"
    hooks:
      - id: dprint
