version: "3"

tasks:
  rtorrent-0.9.8:
    desc: Build rtorrent 0.9.8
    cmds:
      - python build.py rtorrent-0.9.8 {{.CLI_ARGS}}

  rtorrent-0.16.11:
    desc: Build rtorrent 0.16.11
    cmds:
      - python build.py rtorrent-0.16.11 {{.CLI_ARGS}}

  rtorrent-master:
    desc: Build rtorrent master
    cmds:
      - python build.py rtorrent-master {{.CLI_ARGS}}

  qbittorrent-nox:
    desc: Build qbittorrent-nox
    cmds:
      - python build.py qbittorrent-nox {{.CLI_ARGS}}

  all:
    desc: Build all variants
    cmds:
      - task: rtorrent-0.9.8
      - task: rtorrent-0.16.11
      - task: rtorrent-master
      - task: qbittorrent-nox
