FROM busybox:musl@sha256:8635836765b0c4c43970660219739baa58b0883c2e429e4b8918f7dd1519455c AS busybox
FROM {{ base_image }}
{% if debug %}
RUN apt-get update && apt-get install -y gdb && rm -rf /var/lib/apt/lists/*
{% endif %}
COPY --from=busybox /bin/busybox /usr/local/bin/busybox
COPY {{ binary }} /usr/local/bin/rtorrent
{% if shared_deps %}
COPY rtorrent.libs/ /usr/local/bin/rtorrent.libs/
{% endif %}
ENTRYPOINT ["/usr/local/bin/rtorrent"]
