FROM busybox:musl@sha256:8635836765b0c4c43970660219739baa58b0883c2e429e4b8918f7dd1519455c AS busybox
FROM {{ base_image }}
COPY --from=busybox /bin/busybox /usr/local/bin/busybox
COPY {{ binary }} /usr/local/bin/rtorrent
ENTRYPOINT ["/usr/local/bin/rtorrent"]
