FROM busybox:musl@sha256:ea2b9914a16a4ac1981994af97b318f7c7d4db76b580c56177f08bf76f4a0be8 AS busybox
FROM {{ base_image }}
{% if debug %}
RUN apt-get update && apt-get install -y gdb && rm -rf /var/lib/apt/lists/*
{% endif %}
COPY --from=busybox /bin/busybox /usr/local/bin/busybox
COPY {{ binary }} /usr/local/bin/rtorrent
ENTRYPOINT ["/usr/local/bin/rtorrent"]
