name: neptune-docker

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: trim21/neptune

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Clone neptune
        run: git clone --depth 1 https://github.com/trim21/neptune.git /tmp/neptune

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build binary (linux/amd64)
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: "0"
        run: |
          go build \
            -tags release \
            -ldflags="-s -w -X 'neptune/internal/pkg/global.UserAgent=rtorrent/0.9.8/0.13.8' -X 'neptune/internal/core.peerIDPrefix=-TR2930-'" \
            -trimpath \
            -o ${{ github.workspace }}/neptune \
            .
        working-directory: /tmp/neptune

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: neptune.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-disguised
