name: new rtorrent release

on:
  schedule:
    - cron: "8 17 * * *"
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          activate-environment: "true"

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Check for new release
        id: check
        run: uv run python scripts/new-rtorrent-release.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pre-commit
        run: uvx prek run --all-files || true

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "feat: add manifest for latest rtorrent release"
          token: "${{ secrets.PAT }}"
          title: "feat: add manifest for latest rtorrent release"
          branch: auto/rtorrent-release
          body: Automated manifest creation for the latest rtorrent release.
